# Generated by Django 4.0 on 2021-12-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('lastPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dayHigh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dayLow', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
